Pandas Datareader 
https://pandas-datareader.readthedocs.io/en/latest/

In [1]:
#Import dictionaries and libraries
#Pandas Datareader prepares the data in a dataframe for you
#To install Pandas Datareder pip install pandas-datareader
import pandas_datareader as pdr
import datetime as dt

In [10]:
ticker_symbols = ["SPY", "META", "AAPL", "AMZN", "NFLX", "GOOG", "MSFT"]
start = dt.datetime(2002,3,1)
end = dt.datetime(2022,6,30)
data = pdr.get_data_yahoo(ticker_symbols, start).dropna()

In [6]:
data.head()

Attributes   Adj Close                                                         \
Symbols            SPY       META       AAPL       AMZN       NFLX       GOOG
Date
2014-03-27  158.455826  60.970001  17.075377  16.923500  52.025715  27.846546
2014-03-28  159.237076  60.009998  17.056313  16.914499  51.267143  27.922838
2014-03-31  160.541962  60.240002  17.052500  16.818501  50.290001  27.772251
2014-04-01  161.606491  62.619999  17.208494  17.149500  52.098572  28.280355
2014-04-02  162.147308  62.720001  17.237087  17.098000  51.840000  28.272379

Attributes                  Close                        ...       Open  \
Symbols          MSFT         SPY       META       AAPL  ...       NFLX
Date                                                     ...
2014-03-27  33.854599  184.580002  60.970001  19.195000  ...  53.001431
2014-03-28  34.663113  185.490005  60.009998  19.173571  ...  51.459999
2014-03-31  35.256603  187.009995  60.240002  19.169287  ...  51.644287
2014-04-01  35.626461  188.250000  62.619999  19.344643  ...  50.250000
2014-04-02  35.566261  188.880005  62.720001  19.376785  ...  52.237144

Attributes                             Volume                            \
Symbols          GOOG       MSFT          SPY         META         AAPL
Date
2014-03-27  28.322241  39.740002  142383000.0  112650000.0  222031600.0
2014-03-28  27.983171  39.790001  101642000.0   67052000.0  200564000.0
2014-03-31  28.266893  40.430000   99745000.0   53011000.0  168669200.0
2014-04-01  27.859013  41.150002   89193000.0   59291000.0  200760000.0
2014-04-02  29.917362  41.439999   78774000.0   66277000.0  180420800.0

Attributes
Symbols            AMZN        NFLX       GOOG        MSFT
Date
2014-03-27  115328000.0  28672000.0   262719.0  35369200.0
2014-03-28   79736000.0  24699500.0   824257.0  43472700.0
2014-03-31   85950000.0  22125600.0   216593.0  46886300.0
2014-04-01   72002000.0  21338800.0   158434.0  32605000.0
2014-04-02   89510000.0  24194100.0  2942055.0  28666700.0

[5 rows x 42 columns]

In [7]:
data.tail()

Attributes   Adj Close                                                  \
Symbols            SPY        META        AAPL        AMZN        NFLX
Date
2022-07-12  380.829987  163.270004  145.860001  109.220001  174.449997
2022-07-13  378.829987  163.490005  145.490005  110.400002  176.559998
2022-07-14  377.910004  158.050003  148.470001  110.629997  174.779999
2022-07-15  385.130005  164.699997  150.169998  113.550003  189.110001
2022-07-18  381.950012  167.229996  147.070007  113.760002  190.919998

Attributes                               Close                          ...  \
Symbols           GOOG        MSFT         SPY        META        AAPL  ...
Date                                                                    ...
2022-07-12  114.849503  253.669998  380.829987  163.270004  145.860001  ...
2022-07-13  112.186996  252.720001  378.829987  163.490005  145.490005  ...
2022-07-14  111.440002  254.080002  377.910004  158.050003  148.470001  ...
2022-07-15  112.766998  256.720001  385.130005  164.699997  150.169998  ...
2022-07-18  109.910004  254.250000  381.950012  167.229996  147.070007  ...

Attributes        Open                              Volume              \
Symbols           NFLX        GOOG        MSFT         SPY        META
Date
2022-07-12  177.330002  116.838501  265.880005  62219200.0  16639700.0
2022-07-13  170.500000  112.639000  250.190002  84224600.0  16555100.0
2022-07-14  175.559998  110.825996  250.570007  89704800.0  23765200.0
2022-07-15  175.580002  112.962997  255.720001  79016800.0  23172800.0
2022-07-18  192.500000  113.440002  259.750000  63060000.0  23555100.0

Attributes
Symbols           AAPL        AMZN        NFLX        GOOG        MSFT
Date
2022-07-12  77588800.0  54280300.0   6845300.0  24970000.0  35868500.0
2022-07-13  71185600.0  61353800.0  12734400.0  38958000.0  29497400.0
2022-07-14  78140700.0  51163100.0   9039500.0  32366000.0  25102800.0
2022-07-15  76030800.0  83891100.0  16215100.0  34330000.0  29572500.0
2022-07-18  81264900.0  59020600.0  16303000.0  33316500.0  20956300.0

[5 rows x 42 columns]

In [11]:
data.tail()

Attributes   Adj Close                                                  \
Symbols            SPY        META        AAPL        AMZN        NFLX
Date
2022-07-12  380.829987  163.270004  145.860001  109.220001  174.449997
2022-07-13  378.829987  163.490005  145.490005  110.400002  176.559998
2022-07-14  377.910004  158.050003  148.470001  110.629997  174.779999
2022-07-15  385.130005  164.699997  150.169998  113.550003  189.110001
2022-07-18  381.950012  167.229996  147.070007  113.760002  190.919998

Attributes                               Close                          ...  \
Symbols           GOOG        MSFT         SPY        META        AAPL  ...
Date                                                                    ...
2022-07-12  114.849503  253.669998  380.829987  163.270004  145.860001  ...
2022-07-13  112.186996  252.720001  378.829987  163.490005  145.490005  ...
2022-07-14  111.440002  254.080002  377.910004  158.050003  148.470001  ...
2022-07-15  112.766998  256.720001  385.130005  164.699997  150.169998  ...
2022-07-18  109.910004  254.250000  381.950012  167.229996  147.070007  ...

Attributes        Open                              Volume              \
Symbols           NFLX        GOOG        MSFT         SPY        META
Date
2022-07-12  177.330002  116.838501  265.880005  62219200.0  16639700.0
2022-07-13  170.500000  112.639000  250.190002  84224600.0  16555100.0
2022-07-14  175.559998  110.825996  250.570007  89704800.0  23765200.0
2022-07-15  175.580002  112.962997  255.720001  79016800.0  23172800.0
2022-07-18  192.500000  113.440002  259.750000  63060000.0  23555100.0

Attributes
Symbols           AAPL        AMZN        NFLX        GOOG        MSFT
Date
2022-07-12  77588800.0  54280300.0   6845300.0  24970000.0  35868500.0
2022-07-13  71185600.0  61353800.0  12734400.0  38958000.0  29497400.0
2022-07-14  78140700.0  51163100.0   9039500.0  32366000.0  25102800.0
2022-07-15  76030800.0  83891100.0  16215100.0  34330000.0  29572500.0
2022-07-18  81264900.0  59020600.0  16303000.0  33316500.0  20956300.0

[5 rows x 42 columns]